### ISSUE TITLE
Newbie Here... how to stop library debug lines ?

### ISSUE THREAD

**Issue by MopheusDG** [Aircoookie/Espalexa#10]
Hi, I'm trying to add my serial prints to check my code but the library itself prints a LOT of info and I'm not sure how to set the debug OFF in the library. Can you help me ?

By the way, is it normal that there's SO MANY of this messages ? (I mean, like 2 Got UDP! messages every 1 or 2 seconds)

And thanks, the library seems AMAZING ! I was using Fauxmo but wanted some with brightness to use with my devices for so long... Keep this one alive ! You rock :)

`
Got UDP!
NOTIFY * HTTP/1.1
HOST:239.255.255.250:1900
CACHE-CONTROL:max-age=16
LOCATION:http://192.168.0.254:8200/rootDesc.xml
SERVER: 3.14.77 DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.1.5
NT:urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
USN:uuid:4d696e69-44
Got UDP!
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.240:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.24.0
NTS: ssdp:alive
hue-bridgeid: 001788FFFE4AAC68
NT: urn:schemas-upnp-org:device:b
Got UDP!
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.240:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.24.0
NTS: ssdp:alive
hue-bridgeid: 001788FFFE4AAC68
NT: urn:schemas-upnp-org:device:b
Got UDP!
`

**Comment by Aircoookie** [comment]
Hi,

I'm so glad you like Espalexa so much! That I left the debug interface on was an oversight by me, sorry! Tonight I'll update the library to not send debug messages by default. Getting multiple messages per second is perfectly normal, don't worry. In the meantime, if you want to turn off the debug output yourself, go to `C:\Users\<you>\Documents\arduino\libraries\Espalexa-master\src\Espalexa.cpp` and comment out line 14 so it reads `//#define DEBUG_ESPALEXA`. Hope it'll helf fix the issue for you! :)

Thanks for your encouraging words!

**Comment by MopheusDG** [comment]
Thank you. Worked like a charm.
