### ISSUE TITLE
My devices are not found by Echo

### ISSUE THREAD

**Issue by guicovred** [Aircoookie/Espalexa#107]
Hi, i am having discovery issues with my devices. Using EspalexaBasic.ino in a esp32 (DevKit V1) or in esp8266 (Wemos D1 Mini), the device (echo 3rd generation) finds nothing. 

/espalexa:

> Hello from Espalexa!
> 
> Value of device 1 (Luz 1): 0 (Dimmable light)
> Value of device 2 (Luz 2): 0 (Dimmable light)
> Value of device 3 (Luz 3): 0 (Dimmable light)
> Value of device 4 (Luz 4): 0 (Dimmable light)
> Value of device 5 (Luz 5): 0 (Dimmable light)
> 
> Free Heap: 260804
> Uptime: 1523555
> 
> Espalexa library v2.4.4 by Christian Schwinne 2020

Serial output:

> IP address: 192.168.100.233
> Constructing device 1
> Adding device 1
> Constructing device 2
> Adding device 2
> Constructing device 3
> Adding device 3
> Constructing device 4
> Adding device 4
> Constructing device 5
> Adding device 5
> Espalexa Begin...
> MAXDEVICES 10
> Done

> Got UDP!
> M-SEARCH * HTTP/1.1
> HOST: 239.255.255.250:1900
> MAN: "ssdp:discover"
> MX: 1
> ST: urn:dial-multiscreen-org:service:dial:1
> USER-AGENT: Google Chrome/80.0.3987.122 Windows
> 
> 
> Got UDP!
> M-SEARCH * HTTP/1.1
> HOST: 239.255.255.250:1900
> MAN: "ssdp:discover"
> MX: 1
> ST: urn:dial-multiscreen-org:service:dial:1
> USER-AGENT: Google Chrome/80.0.3987.122 Windows
> 
> (repeat this over and over again)

I tried to restart Echo and router but unlucky. I don't see any UDP traffic on port 1900 in my router when i ask Echo to find devices too. (Is it normal?)

**Comment by seriouz** [comment]
My Alexa device (3rd gen) spams the network with UDP Packages, when i say: "Alexa search for new devices!". Does your router block UDP?
