### ISSUE TITLE
How is the conversion from 0-100 to 0-255 being done ?

### ISSUE THREAD

**Issue by MopheusDG** [Aircoookie/Espalexa#11]
Correct me if I'm wrong, but it's not using "round", it's just cutting decimals OFF and adding 1 to the result ?

I'm actually needing to go back to 0-100 values and that's what I found, am I right ?

Thanks !

**Comment by Aircoookie** [comment]
Hi again,

actually the 0-100 to 0-255 conversion is done by the Echo device itself, which then sends a 0-255 value to Espalexa. So I can't tell you how it exactly works, but I also believe its cutting of decimals ("flooring") and adding 1. For going back to 0-100 i'd suggest trying to convert the Espalexa device value to a `float`, dividing it by `2.55` and then converting it back to an integer. I never tried that though, so I'm not sure if it will work!

**Comment by MopheusDG** [comment]
Thanks ! Found a way to do it.
