### ISSUE TITLE
Another discovery issue

### ISSUE THREAD

**Issue by sypheren** [Aircoookie/Espalexa#117]
I'm getting another typical discovery issue, my boards and code which used to work now do not. I'm using FastLED + EspAlexa for my code. 

Connecting to WiFi
Connecting....
Connected to (((WIFI SSDI)))
IP address: 192.168.1.30
Constructing device 1
Adding device 1
Espalexa Begin...
MAXDEVICES 10
Done
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

((**At this point I ask alexa to discover**))

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: upnp:rootdevice
MAN: "ssdp:discover"
MX: 3

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: upnp:rootdevice
MAN: "ssdp:discover"
MX: 3

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: upnp:rootdevice
MAN: "ssdp:discover"
MX: 3

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
MX: 3
ST: ssdp:all

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
MX: 3
ST: upnp:rootdevice

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
MX: 3
ST: ssdp:all

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
MX: 3
ST: upnp:rootdevice

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
MX: 3
ST: ssdp:all

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
MX: 3
ST: upnp:rootdevice

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
USER-AGENT: Google Chrome/81.0.4044.138 Windows

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
ST: upnp:rootdevice
MX: 5

Responding search req...
-----------------------------------

Alexa reports no devices are found. This appears typical of other reports I've seen, but I thought that it had been resolved. Is this common or am I doing something wrong? Code posted below:

```
//#ifdef ARDUINO_ARCH_ESP32
//#include <WiFi.h>
//#else
#define ESPALEXA_DEBUG
#include <ESP8266WiFi.h>
//#endif
#define ESPALEXA_ASYNC
#include <Espalexa.h>

//FastLED
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
#include <FastLED.h>
#define NUM_LEDS 150 //Basically set as high as possible without seeing lag
#define DATAPIN 6 // for some reason the pins are actually correct i.e., D6 --> pin 6
CRGB leds[NUM_LEDS]; //put number of LEDS to run here
int current_r = 0;
int current_g = 0;
int current_b = 0;


// prototypes
boolean connectWifi();

//callback function prototype
void colorLightChanged(uint8_t brightness, uint32_t rgb);

// Wifi setup
const char* ssid = "my ssid";
const char* password = "my password";

boolean wifiConnected = false;

Espalexa espalexa;

void setup()
{
  Serial.begin(115200);
  // Initialise wifi connection
  wifiConnected = connectWifi();

  //add device if wifi is good
  if(wifiConnected){
    espalexa.addDevice("Fauxllips Hue Light", colorLightChanged);
    espalexa.begin();
    
  } else
  {
    while (1) {
      Serial.println("Cannot connect to WiFi. Please check data and reset the ESP.");
      delay(2500);
    }
  }

  //set up fastled
  FastLED.addLeds<WS2812B, DATAPIN, GRB>(leds, NUM_LEDS);
  //pinMode(LED_BUILTIN, OUTPUT);
  FastLED.clear();
  for(int dot = 0; dot < 5; dot++) { 
    leds[dot].r = 10*(dot + 1);
    leds[dot].g = 10*(dot + 1);
    leds[dot].b = 10*(dot + 1);
  }
  FastLED.show();
  
}
 
void loop()
{
   espalexa.loop();
   delay(5);
}

//the color device callback function has two parameters
void colorLightChanged(uint8_t brightness, uint32_t rgb) {
 
  //deal with leds
  current_r = ((rgb >> 16) & 0xFF);
  current_g = ((rgb >>  8) & 0xFF);
  current_b = (rgb & 0xFF); 
  Serial.print("Actual values: RED: ");
  Serial.print(current_r);
  Serial.print(", GREEN: ");
  Serial.print(current_g);
  Serial.print(", BLUE: ");
  Serial.print(current_b);
  Serial.print("Brightness: ");
  Serial.print(brightness);
  Serial.println(rgb & 0xFF);
  Serial.println();
  //do what you need to do here, for example control RGB LED strip
  
  //update leds 
  for(int dot = 0; dot < NUM_LEDS; dot++) { 
    leds[dot].r = (int)(current_r * brightness)/255;
    leds[dot].g = (int)(current_g * brightness)/255;;
    leds[dot].b = (int)(current_b * brightness)/255;;
  }
  FastLED.show();
}

// connect to wifi – returns true if successful or false if not
boolean connectWifi(){
  boolean state = true;
  int i = 0;
  
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.println("");
  Serial.println("Connecting to WiFi");

  // Wait for connection
  Serial.print("Connecting...");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    if (i > 40){
      state = false; break;
    }
    i++;
  }
  Serial.println("");
  if (state){
    Serial.print("Connected to ");
    Serial.println(ssid);
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
  }
  else {
    Serial.println("Connection failed.");
  }
  return state;
}
```

**Comment by Aircoookie** [comment]
Thank you for reporting! From the log, this seems to be exactly the same symptoms as #92 so we'll be tracking there :)
