### ISSUE TITLE
Type of device.

### ISSUE THREAD

**Issue by rogerespinoza** [Aircoookie/Espalexa#126]
Hello, sorry, I would like to know if the library provides me with the option to configure the type of device shown in the Alexa App, such as Switch, plug, etc., and if it is possible to add more than 1 esp82 66 connected on the same network. Thank you very much in advance.

**Comment by MVFarkas** [comment]
Roger, as far as i know the Espalexa only emulate Hue Lights (OnOff, Dimmable, Color, etc.). 

To emulate a plug, you can use the Wemo Emulator (you can find here in github).

About the number of devices (ESP8266) connected on the same network... yes, you can have more than 1 connected. I'm doing it with ESP32 and so far I haven't had any problems.

**Comment by rogerespinoza** [comment]
> Roger, que yo sepa, el Espalexa solo emula Hue Lights (OnOff, Dimmable, Color, etc.).
> 
> Para emular un complemento, puede usar el emulador de Wemo (puede encontrarlo aquí en github).
> 
> Acerca de la cantidad de dispositivos (ESP8266) conectados en la misma red ... sí, puede tener más de 1 conectado. Lo estoy haciendo con ESP32 y hasta ahora no he tenido ningún problema.

Thank you, you have resolved my question.
