### ISSUE TITLE
JSON format expected by ESPAlexa ?

### ISSUE THREAD

**Issue by MopheusDG** [Aircoookie/Espalexa#13]
Hi, I'm trying to build an android application to be able to turn on/off devices and also set specific "brightness" to each device, and my question is:

What JSON format is ESPAlexa expecting ? I tried with the HUE format but I'm not sure how to specific each device. For example I tried posting to:

http://_MY_ESP_IP_:80/api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1/state

This JSON: {"on":false, "bri":0}

Usually that code, using my Hue App ID instead of yours of course, is enough, but in this case, I get a success response but no light is activated or changed. Ideas of my mistake ?

Thanks a lot.

**Comment by MopheusDG** [comment]
Hi, sorry found my own answer. You cannot send ON:False and BRI together, is one or the other. Example for future references or help some looser like me :loop: :

JSON for OFF: {"on":false}
JSON for BRI and/or ON: {"bri":254}
JSON for ON (Last value of Brightness): {"on":true}

Sorry for inconvenience.

**Comment by Aircoookie** [comment]
Hi, great that you already figured it out! Good luck with your application :)
