### ISSUE TITLE
espalexa react abnormally

### ISSUE THREAD

**Issue by chau-ba-thong** [Aircoookie/Espalexa#130]
hi, every one
i 've used espalexa to control a fan and a lamp, beside i had two Sonoff switch from Ewelink to control 2 other devices from few months ago. every thing is OK till a week ago. all 4 devices still work well, but Alexa always say:"the device is not responding, please check network connection or power supply" when i command turn on/off the fan and the lamp (that created by espalexa), and just say OK as normal with the 2 Sonoff. !!!
i've tried to reset the echo dot, but cannot solved. any idea?

**Comment by barneyz** [comment]
hi, try to delete the espalexa-devices in the alexa-app or in alexa account in browser and call alexa searching  for new devices. If this dis not work the first time, try it again...

**Comment by chau-ba-thong** [comment]
Hi barneyz, i remove and discover three times, but still cannot solve the problem, any other idea?

**Comment by chau-ba-thong** [comment]
hi,
i've found few people raised the same problem with us, but i couldn't find the exact way to solve the problem from any one. so i temporariy close my issue. hope a solution in the future!!

**Comment by chau-ba-thong** [comment]
hi ledsi,
i'm back  now. did you solve the problem not responding of alexa? if not, do as the guy EhudB have posted  in this link https://github.com/Aircoookie/Espalexa/pull/88
thanks to his guide (a little change in espalexa.h), my alexa now say OK as before, after doing a command successfully. Hope you got the same result !
