### ISSUE TITLE
Alexa does not discover any device ESP8266 and ESP32

### ISSUE THREAD

**Issue by viamarit** [Aircoookie/Espalexa#144]
Now two days that Alexa do not recognize the devices, also with the example programs, the same for fauxmo.
This is the debug for the ExampleBasic:
16:27:49.247 -> 
16:27:49.247 -> Connecting to WiFi
16:27:49.247 -> Connecting...........
16:27:54.226 -> Connected to Viamar-FRITZ!Box
16:27:54.226 -> IP address: 192.168.1.49
16:27:54.226 -> Constructing device 1
16:27:54.226 -> Adding device 1
16:27:54.226 -> Constructing device 2
16:27:54.226 -> Adding device 2
16:27:54.226 -> Adding device 3
16:27:54.226 -> Espalexa Begin...
16:27:54.226 -> MAXDEVICES 10
16:27:54.226 -> Done
16:28:08.028 -> Got UDP!
16:28:08.028 -> M-SEARCH * HTTP/1.1
16:28:08.028 -> HOST: 239.255.255.250:1900
16:28:08.028 -> ST: ssdp:all
16:28:08.061 -> MAN: "ssdp:discover"
16:28:08.061 -> MX: 3
16:28:08.061 -> 
16:28:08.061 -> 
16:28:08.061 -> Responding search req...
16:28:08.061 -> Got UDP!
16:28:08.061 -> M-SEARCH * HTTP/1.1
16:28:08.061 -> HOST: 239.255.255.250:1900
16:28:08.061 -> ST: upnp:rootdevice
16:28:08.061 -> MAN: "ssdp:discover"
16:28:08.061 -> MX: 3
16:28:08.061 -> 
16:28:08.061 -> 
16:28:08.061 -> Responding search req...
16:28:08.061 -> Got UDP!
16:28:08.061 -> M-SEARCH * HTTP/1.1
16:28:08.061 -> HOST: 239.255.255.250:1900
16:28:08.061 -> ST: ssdp:all
16:28:08.061 -> MAN: "ssdp:discover"
16:28:08.061 -> MX: 3
16:28:08.061 -> 
16:28:08.061 -> 
16:28:08.061 -> Responding search req...
16:28:08.061 -> Got UDP!
16:28:08.061 -> M-SEARCH * HTTP/1.1
16:28:08.061 -> HOST: 239.255.255.250:1900
16:28:08.095 -> ST: upnp:rootdevice
16:28:08.095 -> MAN: "ssdp:discover"
16:28:08.095 -> MX: 3
16:28:08.095 -> 
16:28:08.095 -> 
16:28:08.095 -> Responding search req...
16:28:08.095 -> Got UDP!
16:28:08.095 -> M-SEARCH * HTTP/1.1
16:28:08.095 -> HOST: 239.255.255.250:1900
16:28:08.095 -> ST: ssdp:all
16:28:08.095 -> MAN: "ssdp:discover"
16:28:08.095 -> MX: 3
16:28:08.095 -> 
16:28:08.095 -> 
16:28:08.095 -> Responding search req...
16:28:08.095 -> Got UDP!
16:28:08.095 -> M-SEARCH * HTTP/1.1
16:28:08.095 -> HOST: 239.255.255.250:1900
16:28:08.095 -> ST: upnp:rootdevice
16:28:08.095 -> MAN: "ssdp:discover"
16:28:08.095 -> MX: 3
16:28:08.095 -> 
16:28:08.095 -> 
16:28:08.095 -> Responding search req...
16:28:08.297 -> # Responding to description.xml ... #
16:28:08.297 -> 
16:28:08.297 -> Send setup.xmlNot-Found HTTP call:
16:28:08.331 -> URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
16:28:08.331 -> Body: 
16:28:08.331 -> AlexaApiCall
16:28:08.331 -> ok
16:28:08.331 -> l0
16:28:08.331 -> lAll
16:28:08.365 -> Not-Found HTTP call:
16:28:08.365 -> URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/204504193
16:28:08.365 -> Body: 
16:28:08.365 -> AlexaApiCall
16:28:08.365 -> ok
16:28:08.365 -> l204504193
16:28:08.365 -> 1
16:28:08.365 -> Not-Found HTTP call:
16:28:08.365 -> URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/204504194
16:28:08.399 -> Body: 
16:28:08.399 -> AlexaApiCall
16:28:08.399 -> ok
16:28:08.399 -> l204504194
16:28:08.399 -> 2
16:28:08.399 -> Not-Found HTTP call:
16:28:08.399 -> URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/204504195
16:28:08.399 -> Body: 
16:28:08.399 -> AlexaApiCall
16:28:08.399 -> ok
16:28:08.399 -> l204504195
16:28:08.399 -> 3
16:28:08.433 -> Not-Found HTTP call:
16:28:08.433 -> URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights
16:28:08.433 -> Body: 
16:28:08.433 -> AlexaApiCall
16:28:08.433 -> ok
16:28:08.433 -> l0
16:28:08.433 -> lAll
16:28:08.771 -> Got UDP!
16:28:08.771 -> M-SEARCH * HTTP/1.1
16:28:08.771 -> HOST: 239.255.255.250:1900
16:28:08.771 -> MAN: "ssdp:discover"
16:28:08.771 -> MX: 1
16:28:08.771 -> ST: urn:dial-multiscreen-org:service:dial:1
16:28:08.771 -> USER-AGENT: Google Chrome/86.0.4240.111 Windows
16:28:08.771 -> 
16:28:08.771 ->

**Comment by navinremala** [comment]
me also got same type of problem,
