### ISSUE TITLE
PlatformIO not updating to 2.5.0 

### ISSUE THREAD

**Issue by DadelNet** [Aircoookie/Espalexa#157]
Hi, I am a newbie. 

I installed the Espalexa library in PlatformIO but it does not seem to :
1. show the version no 
2. update to 2.5.0

I manually overwrote the 2 .cpp and .h files in my PIO project library repository with the files from Gihub, and Espalexa works absolutely fine : it is really great library and quite easy to use by following the examples. Thanks.

However, I am not sure it is the right way ?

This is what it shows in PIO : 
              Espalexa by Christian Schwinne
              Library to control an ESP module with the Alexa voice assistant

              Library Dependencies platformio.ini
              The PlatformIO Registry is fully compatible with **Semantic Versioning and its "version" scheme <major>.<minor>.<patch>**. You can declare library dependencies in "platformio.ini" configuration file using lib_deps option.
              
              # platformio.ini – project configuration file
              [env:my_build_env]
              framework = arduino
              lib_deps =
                **aircoookie/Espalexa @ 0.0.0-alpha+sha.09981160b5**      

Should this follow the Semantic Versioning standard ?

**Comment by Aircoookie** [comment]
Hi!
Espalexa does follow semantic versioning, so you _should_ be able to include 2.5.0 using the `aircoookie/Espalexa @ 2.5.0` dependency.

That said, I don't know whether Espalexa is in the PIO library index (it includes the "most common" libraries, I don't know if that encompasses every official Arduino library). If you want to be on the safe side, you can include Espalexa like this: `https://github.com/Aircoookie/Espalexa.git @ ~2.5.0`, however this will require that you have Git client installed on your machine.

**Comment by eos1d3** [comment]
I found it is the bug of PlatformIO. This problem exists for a long long time. When you use newer version of library, it won't update until you manually delete one of the directory. I can remember the name at the moment. 

lib_deps parameters work if you remove that directory.

**Comment by DadelNet** [comment]
Thank you both for replying. 
@ Aircookies : I tried as suggested but  it failed also. Here is the Build error code. Can you suggest a way forward ?
 
> Executing task in folder Blind_Controller: C:\Users\Laptop\.platformio\penv\Scripts\pio.exe run <

Processing d1_mini (platform: espressif8266; board: d1_mini; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (2.6.2) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing git+https://github.com/Aircoookie/Espalexa.git @ ~2.5.0
git version 2.29.2.windows.2
Cloning into 'C:\Users\Laptop\.platformio\.cache\tmp\pkg-installing-jrurgmh5'...
PackageException: Package version 0.0.0+sha.6cc9651 doesn't satisfy requirements ~2.5.0 based on PackageMetaData <type=library name=Espalexa version=0.0.0+sha.6cc9651 spec={'owner': None, 'id': None, 'name': 'Espalexa', 'requirements': '~2.5.0', 'url': 'git+https://github.com/Aircoookie/Espalexa.git'}:
  File "C:\Users\Laptop\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 170:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\Laptop\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\Laptop\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\Laptop\.platformio\platforms\espressif8266\builder\main.py", line 238:
    target_elf = env.BuildProgram()
  File "C:\Users\Laptop\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:      
    return self.method(*nargs, **kwargs)
  File "C:\Users\Laptop\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 62:    
    env.ProcessProjectDeps()
  File "C:\Users\Laptop\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:      
    return self.method(*nargs, **kwargs)
  File "C:\Users\Laptop\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 140:
    project_lib_builder = env.ConfigureProjectLibBuilder()
  File "C:\Users\Laptop\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\Users\Laptop\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py", line 1062:
    project.install_dependencies()
  File "C:\Users\Laptop\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py", line 898:
    lm.install(spec)
  File "c:\users\laptop\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 49:
    spec, silent=silent, skip_dependencies=skip_dependencies, force=force
  File "c:\users\laptop\.platformio\penv\lib\site-packages\platformio\package\manager\library.py", line 86:
    force=force,
  File "c:\users\laptop\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 97:
    pkg = self.install_from_url(spec.url, spec, silent=silent)
  File "c:\users\laptop\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 152:
    return self._install_tmp_pkg(pkg_item)
  File "c:\users\laptop\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 172:
    tmp_pkg.metadata,
========================================================== [FAILED] Took 18.23 seconds ==========================================================
The terminal process "C:\Users\Laptop\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by maxgerhardt** [comment]
@Aircoookie 
> Espalexa does follow semantic versioning, so you should be able to include 2.5.0 using the aircoookie/Espalexa @ 2.5.0 dependency.

Your repository has a library.json so information will be sourced from there instead of the library.properties.

However the `library.json` file has no version info ([docs](https://docs.platformio.org/en/latest/librarymanager/config.html#version)), so the PlatformIO crawler will also not update the version info.

Can you update the `library.json` accordingly? https://platformio.org/lib/show/5525/Espalexa should be auto.updated some time (a day) after that then.

**Comment by DadelNet** [comment]
Thanks Aircookie, all working with your advice.

**Comment by maxgerhardt** [comment]
@Aircoookie  the library is still not updating because the 2.5.0 tag of this repository doesn't have that version field. Can you do re-tag so that that's good? (https://community.platformio.org/t/espalexa-pio-library-not-updating-to-2-5-0/18157/4?u=maxgerhardt)
