### ISSUE TITLE
Basic question using ESP32

### ISSUE THREAD

**Issue by mcpacific** [Aircoookie/Espalexa#161]
I have gone through the examples but I do not see any code that indicates which GPIO to connect to my data pin for my WS2812B strip. I'm guessing I'm missing something very basic. 

I was able to upload the examples and I find the devices in the Alexa app, but I'm unable to actually do anything with them (even though I turn lights on and change colors in the app). The examples don't show any data pin configurations, so how do I get the ESP32 to communicate with my WS2812B LED strip?

**Comment by digi-thomas2003** [comment]
In the examples there are no strips connected. The EspalexaColor just prints out the color values via the serial monitor.
You need **another library** for your led strips (e.g. Adafruit NeoPixel, NeoPixelBus or FastLED).

**Comment by mcpacific** [comment]
> In the examples there are no strips connected. The EspalexaColor just prints out the color values via the serial monitor.
> You need **another library** for your led strips (e.g. Adafruit NeoPixel, NeoPixelBus or FastLED).

Great, I think I got it figured out. Thank you!
