### ISSUE TITLE
How to add thermostat

### ISSUE THREAD

**Issue by harymk** [Aircoookie/Espalexa#174]
Please tell me how to add thermostat

**Comment by harymk** [comment]
Hello some one please reply

**Comment by MechApe** [comment]
Hi Harymk, it doesn't sound like ESPAlexa would work in your case. But, could you explain a little more about what you want to do?

**Comment by harymk** [comment]
I need to change device models. Like fan, thermostat,

**Comment by Aircoookie** [comment]
Changing the device type as displayed in the Alexa app is not possible.
However, Alexa will still recognize e.g. "Set heater to 21 degrees" and set the Espalexa device to 21%.
You can get this value using `espalexa.toPercent(brightness);` and just use it as the degrees input value for your thermostat.

**Comment by harymk** [comment]
Ok thanks

**Comment by harymk** [comment]
How can i set device status on/off and brightness suparated. Now there is one option i see in code Setvalue().

**Comment by Aircoookie** [comment]
`setState()` should work fine for on/off

**Comment by harymk** [comment]
There is a problem. I changed on off state, brightness value be changed. is there any solution for that
