### ISSUE TITLE
ESPALEXA do not communicate with alexa or discover any device from today - 05-05-2021

### ISSUE THREAD

**Issue by samratnarvekar** [Aircoookie/Espalexa#176]
Dear Christian,

From today morning i am not able to use alexa to communicate with my devices in esp8266 using espalexa, I have 4 esp8266, all stopped working at same time since today morning. I checked the serial monitor, the esp8266 gets connected to wifi and tries to communicate with alexa, but when i try giving voice command to turn on or off any device , alexa says that the device is unresponsive. Also tried turning On and OFF through alexa APP, still it show unresponsive under devices. I think alexa has updated itself and blocked the SSDP pls help. My email is samrat.narvekar@gmail.com . Also would like to know when is the new espalexa update become available?

Best Regards

Samrat

**Comment by 20pyro00** [comment]
Hi again :)

I think i fixed it. I deleted the Espalexa folder in libraries and redownloaded the master. Then i reopened Arduino and uploaded the code. Now my Light is working again :D

Hope it fixes it for you, too.

Cheers

**Comment by esrpradeep** [comment]
Hi @20pyro00, can you please explain the steps? it did't work for me that way!

**Comment by samratnarvekar** [comment]
Even my issue has resolved, but a miracle, it got resolved on its own, i have 4 esp8266,  1 esp32, with 28 devices. All have stopped together and now all started on its own, this was an alexa issue for sure and they resolved it, because i didnt do much r&d

**Comment by 20pyro00** [comment]
> Update: It worked!!! Thanks, 20pyro00.
> 
> steps that I followed:
> 
> 1. As suggested by 20pyro00, removed the old Espalexa folder and replaced it with the latest library folder from the master branch.
> 2. Closed Arduino and re-opened Arduino with my project.
> 3. Compiled/Build and flashed my device.
> 4. Rebooted Echo Dot (3rd Gen). - waited for some time to restart the device.
> 5. Searched new devices (removed older discovered device), and it got added!
> 
> It works fine!
> 
> Cheers!!!
> 
> > > Hi @20pyro00, can you please explain the steps? it didn't work for me that way!

Thanks for the detailed explanation 🙂
I am glad I could help. Have a nice week!

Cheers

Tobias

**Comment by samratnarvekar** [comment]
Thank u all for their contribution and sugesstions
