### ISSUE TITLE
Is there anyone that can help? The Espalexa creator? 12 days passed from my post and still no answer.

### ISSUE THREAD

**Issue by tiristor45** [Aircoookie/Espalexa#204]
Is there anyone that can help? The Espalexa creator? 12 days passed from my post and still no answer.

_Originally posted by @SparkyHellas in https://github.com/Aircoookie/Espalexa/issues/201#issuecomment-1073119632_

**Comment by Aircoookie** [comment]
I'm sorry, but I don't actively maintain Espalexa at this time. Perhaps I will improve its reliability soon, but I can't promise it.
