### ISSUE TITLE
I say find my devices with Amazon Alexa, it finds only 1 device

### ISSUE THREAD

**Issue by demir30** [Aircoookie/Espalexa#228]
Hello, 
I installed espalexa on my NodeMCU card and there are 3 lamps in the program.
After the installation is completed; I say find my devices with Amazon Alexa, it finds only 1 device and turns it on and off only. The other 2 devices are not visible.
But when I want to delete the device from Alexa; I delete the device, then the 2nd device appears, I delete it too, the 3rd device appears, I delete it too, and it's done.
But I can't have it on 3 devices at the same time?
Please help urgently...
[2.txt](https://github.com/user-attachments/files/17235909/2.txt)

**Comment by kbssa** [comment]
The same here. I think that they have changed the philips hue protocol.

**Comment by anshumanpatra** [comment]
I also have the same issue.
Please help.

**Comment by engmarconi** [comment]
I have the same issue, although when I ping on http://[espIP]/espalexa, I got the three devices.
Help please

**Comment by anshumanpatra** [comment]
I called Amazon customer care, and they said they can see all the discover devices. However, in the app, only one channel is showing up.

The problem is that in the app, it is displaying only one channel for each device.

I am on a prototype design and just stuck.
Please help.

**Comment by anshumanpatra** [comment]
Did you try it?

**Comment by werneckpaiva** [comment]
Same here. I used the https://github.com/vintlabs/fauxmoESP alternative and it worked for me.
I even created a pull request to add support to rgb color.
https://github.com/vintlabs/fauxmoESP/pull/260

**Comment by BoeckEH** [comment]
I switched off from FauxMo as it had the same issue back a couple years ago.  My issue is it doesn't find all my set up devices, just randomly some.

**Comment by anshumanpatra** [comment]
https://github.com/vintlabs/fauxmoESP 

this library also having same issue.

**Comment by ams-hh** [comment]
In FauxmoESP Library Issue Section
[https://github.com/vintlabs/fauxmoESP/issues/259](url)
a second user confirms  a proposed solution as successful.
But I have no idea how to transfer this to ESPAlexa. 
(FauxmoESP does not support color control, so it is no replacement)

**Comment by ams-hh** [comment]
All right ....

Thanks to user PakoCosmos at fauxmoESP section
[https://github.com/vintlabs/fauxmoESP/issues/259](https://github.com/Aircoookie/Espalexa/issues/url)

I could now successfully identify the place in the ESPalexa Lib to transfer his
solution. At my environment it works perfectly. I now have again three separate
devices as usual and can address them by voice.
Don't know if it works for erveryone.
But maybe someone can verify and report.

fauxmoESP lib version 2.7.0
File: espalexa.h
Line 120 (Start of function encodeLightId)

`  
void encodeLightId(uint8_t idx, char* out)
  {
    uint8_t mac[6];
    WiFi.macAddress(mac);

//OLD !!!!!!!!!!!!!!
//    sprintf_P(out, PSTR("%02X:%02X:%02X:%02X:%02X:%02X:00:11-%02X"), mac[0],mac[1],mac[2],mac[3],mac[4],mac[5], idx);

//NEW !!!!!!!!!!!!!!
    String mymac = WiFi.macAddress();
    sprintf_P(out, PSTR("%02X:%s:AB-%02X"), idx, mymac.c_str(), idx);
  }
`

Good luck

**Comment by anshumanpatra** [comment]
Their has not lib version 2.7.0 
We are using lib version 3.4.0

Please let us know if any solution available. 
Thank.

**Comment by ams-hh** [comment]
My fault.
Must be ESPalexa lib version 2.7.0

**Comment by anshumanpatra** [comment]
Can you please share me a link of this version to download?

**Comment by anshumanpatra** [comment]
Thank You very much. 
This is working at my side also.

**Comment by 3vilson** [comment]
> All right ....
> 
> Thanks to user PakoCosmos at fauxmoESP section [https://github.com/vintlabs/fauxmoESP/issues/259](https://github.com/Aircoookie/Espalexa/issues/url)
> 
> I could now successfully identify the place in the ESPalexa Lib to transfer his solution. At my environment it works perfectly. I now have again three separate devices as usual and can address them by voice. Don't know if it works for erveryone. But maybe someone can verify and report.
> 
> ESPalexa lib version 2.7.0 File: espalexa.h Line 120 (Start of function encodeLightId)
> 
> ` void encodeLightId(uint8_t idx, char* out) { uint8_t mac[6]; WiFi.macAddress(mac);
> 
> //OLD !!!!!!!!!!!!!! // sprintf_P(out, PSTR("%02X:%02X:%02X:%02X:%02X:%02X:00:11-%02X"), mac[0],mac[1],mac[2],mac[3],mac[4],mac[5], idx);
> 
> //NEW !!!!!!!!!!!!!! String mymac = WiFi.macAddress(); sprintf_P(out, PSTR("%02X:%s:AB-%02X"), idx, mymac.c_str(), idx); } `
> 
> Good luck
❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤
**❤❤❤❤❤❤❤_Thank You VERY MUCH !!!!!!!!!!!!!!!!!!!!!!! OMG_❤❤❤❤❤❤❤**
❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤

**Comment by anshumanpatra** [comment]
Great job.
Thank You.

**Comment by werneckpaiva** [comment]
@ams-hh  Pull Request?

**Comment by lwillgu** [comment]
> String mymac = WiFi.macAddress();
> sprintf_P(out, PSTR("%02X:%s:AB-%02X"), idx, mymac.c_str(), idx);

This is the first time I've ever commented on really any forum or post. YOU SAVED ME I CANNOT THANK YOU ENOUGH!!!!!!!!!!!!!!!! I finally got it working!!!
