### ISSUE TITLE
pushed button 

### ISSUE THREAD

**Issue by simmorga** [Aircoookie/Espalexa#26]
Does the Philips API allow the button function to open the door lock? 
thank you.

**Comment by Aircoookie** [comment]
Excuse me, I don't know which button and door lock you mean. Are you trying to control a door lock with Alexa using my library? You can easily extend your code to support a button connected to ESP8266. Be aware though that it is not secure to control a door lock with Alexa.

**Comment by simmorga** [comment]
excuse the pulling. I would like that from the app alexa does not appear "on" and "off" but "push" you can do?

**Comment by Aircoookie** [comment]
That is not directly supported by Alexa. However, it is possible to turn the virtual device off automatically directly after Alexa turned it on. It should come close to the push button function you want.

Here is some modified example code which does that:
https://gist.github.com/Aircoookie/230fe201729766c7bc4b2dc81327722c
