### ISSUE TITLE
Turn off internal LED

### ISSUE THREAD

**Issue by badenzer** [Aircoookie/Espalexa#27]
Is there an option to turn off the internal (blue) LED of the ESP8266 on my NodeMCU?

**Comment by Aircoookie** [comment]
Yes, you can select a different LED strip pin in "NpbWrapper.h". Theoretically, gpio2 is most reliable, but i found no issue using gpio5.

**Comment by badenzer** [comment]
Perfect. Many Thanks.
I've chosen gpio3. (At gpio5, I get this warning: Software BitBang will be used because of your selected LED pin. This may cause flicker. Use GPIO 2 or 3 for best results.)

**Comment by Aircoookie** [comment]
Awesome! Also, I just noticed that this issue applied to WLED and not Espalexa. Closing.
