### ISSUE TITLE
HSV instead of RGB?

### ISSUE THREAD

**Issue by ChristianKnorr** [Aircoookie/Espalexa#34]
Hey,
is it possible to get HSV value instead of RGB?
For this function:
```c++
espalexa.addDevice("Light", colorLightChanged);
[...]
void colorLightChanged(uint8_t brightness, uint32_t rgb) { [...] }
```
i need RGB, but for my next step i need HSV in my function.

I think a RGB->HSV-conversion is a bad idea because Alexa tell Espalexa hue|sat|bri|ct 😉

Thank you 😄

**Comment by Aircoookie** [comment]
Hey,
of course that is possible! Follow the basic example or readme on how to create an EspalexaDevice object :)
With that, additional functions are available and you can do something like:

```cpp
void colorLightChanged(uint8_t brightness, uint32_t rgb)
{
  uint16_t hue = colorDevice->getHue();
  byte sat = colorDevice->getSat();
  uint16_t ct = colorDevice->getCt();
}
```

Keep in mind that when setting color temperature (white spectrum), Hue and Sat will not be updated.
Also, if hue and sat are updated, ct will default to 500. You can check wheter Hue+Sat or ct are currently valid with `colorDevice->IsColorTemperatureMode()`

**Comment by ChristianKnorr** [comment]
Thank you 😄
If i'm finished i will give you the next example 😉

**Comment by ChristianKnorr** [comment]
I don't understand ```colorDevice->isColorTemperatureMode()```.
For the first time i change color or ct it is "1", and every next time(s) it is "0", but it doesn't matter it's colored or whited...

```c++
[before setup]
uint8_t iscolor1;
[...]
[in setup]
  device1 = new EspalexaDevice("Oberschrank rechts", colorLightChanged1, 0);
  espalexa.addDevice(device1);
[...]
[after loop]
void colorLightChanged1(uint8_t brightness, uint32_t rgb) {
  iscolor1 = device1->isColorTemperatureMode();
  Serial.print("iscolor1: "); Serial.println(iscolor1);
//  [up to here i want to separate witch 'if']
  uint16_t hue = device1->getHue();
  byte sat = device1->getSat();
  uint16_t ct = device1->getCt();
}
```

**Comment by ChristianKnorr** [comment]
Aaaargh sorry my failure 😁
what you can't see is the rest of my function in which i play with ```device1->setValue()``` and ```device1->setColor(hue, sat);``` so i haven't to wonder 😜
