### ISSUE TITLE
Async is not compatible with delay()

### ISSUE THREAD

**Issue by debsahu** [Aircoookie/Espalexa#36]
Mentions of recommendations to not use delay() with Async:

1. https://github.com/marvinroger/async-mqtt-client/blob/master/docs/1.-Getting-started.md#fully-featured-sketch
2. https://github.com/me-no-dev/ESPAsyncWebServer#important-things-to-remember
3. https://github.com/Links2004/arduinoWebSockets#limitations-for-async

https://github.com/Aircoookie/Espalexa/blob/fdee31827a62c97742fc723749ef5a63b67ca971/examples/EspalexaWithAsyncWebServer/EspalexaWithAsyncWebServer.ino#L72

**Comment by Aircoookie** [comment]
Thank you, but the links you posted all seem to discourage using delay() in the webserver callbacks. That is to be expected and similar to interrupt handlers, where blocking functions are also a bad idea.
The sources don't mention anything about using delay() in the loop being a bad practise though.

**Comment by debsahu** [comment]
Maybe you are right. This was a requirement for [TaskScheduler](https://github.com/arkhipenko/TaskScheduler), and I confused it up with Async.
