### ISSUE TITLE
Which amazon echo supports color natively

### ISSUE THREAD

**Issue by krulkip** [Aircoookie/Espalexa#39]

**Comment by Aircoookie** [comment]
I'm unsure about the exact models and regions, however in Germany Echo 2 and Echo Plus seem to support it while Echo Dot 2 doesn't yet.

**Comment by krulkip** [comment]
I tried Echo plus and Echo dot 3 and both work. Echo 1st gen does not.

**Comment by Aircoookie** [comment]
As of v2.4.0, Echo 1st gen should now be supported for color devices!
