### ISSUE TITLE
Is this firmware for emulating a device or hub?

### ISSUE THREAD

**Issue by mano1979** [Aircoookie/Espalexa#46]
I would like to know if this firmware makes your esp a lightbulb or a hub to control the lights?

**Comment by Aircoookie** [comment]
Hi, I would say this library works more like a hub in that it allows you to emulate multiple "virtual" lightbulbs to Alexa. How many lightbulbs ("EspalexaDevices") you want to emulate and what the virtual devices should do (e.g. trigger GPIO, or send control request to other network devices) is your choice completely.

**Comment by mano1979** [comment]
So it is not possible to have it emulate just one bulb and use a couple of other esp's to do the same?
I assume that you can use this only once in your network?

**Comment by Aircoookie** [comment]
No, it works with as many ESPs as you want! I'm using Espalexa in my WLED software and I have 15 ESP devices in my network, all working fine.
