### ISSUE TITLE
Does not discover devices

### ISSUE THREAD

**Issue by CodeNoMore** [Aircoookie/Espalexa#5]
Using the basic example supplied in the library.
All devices are setup correctly and show as described in the no discover section of the readme.
Built using 8266 versions 2.3.0, 2.4.0-rc2, and 2.4.0 with still no discovery.
The network contains a mix of Gen1 and Gen2 Echo's/Dots.
There are messages on the serial port but none seem to be related to the new device definitions. 
I do not have a Hue bridge and the Alexa Hue skill does not seem to be able to be installed without a bridge so is it required to have this in order for the API to be accessed and discovery to complete?
Thanks.

**Comment by Aircoookie** [comment]
Hi @CodeNoMore ,

sorry for the trouble. First of all, you don't need a Hue bridge. Espalexa merely uses the same protocols (it emulates some parts of the hue bridge).
I believe the problem may be related to a similar issue here https://github.com/Aircoookie/WLED/issues/3 in my other project. I've had forgotten to add the fix to Espalexa, but I did just now.
Please download the new version and try again. Also make sure your router has UPnP enabled.

Thanks for your support of the project!

**Comment by CodeNoMore** [comment]
Yes, thank you, your library update has corrected the discovery issue I was having.
Now I can proceed with my full implementation.

Thank you for creating this library as it enhances the DIY Alexa capabilities.
