### ISSUE TITLE
Setting temperature

### ISSUE THREAD

**Issue by krulkip** [Aircoookie/Espalexa#52]
In the read.me it mentions.
_"It allows you to set a ranged value (e.g. Brightness, Temperature) additionally to standard on/off control. For example, you can say "Alexa, turn the light to 75% / 21 degrees""._
Can you please show an example of how this is done

**Comment by Aircoookie** [comment]
Sure! You just say "Alexa, set heating (or whatever device name) to 21 degrees" (or 70 if you prefer fahrenheit). Then, in the callback function, you add `byte degrees = espalexa.toPercent(brightness)`:

```cpp
void firstLightChanged(uint8_t brightness) {
    byte degrees = espalexa.toPercent(brightness);

    if (brightness) {
      Serial.print("ON, set temperature to ");
      Serial.println(degrees);
    } else
    {
      Serial.println("OFF");
    }
}
