### ISSUE TITLE
device name conflict

### ISSUE THREAD

**Issue by robademar** [Aircoookie/Espalexa#53]
I went crazy for 2 days because I was not able to get a command in my code.
What happened is the following:
I converted a previous sketch to use espalexa.  So used the same device name used before.
Device was discovered, command sent but nothing received by my program.
Delete device and try again, same . **Power off** esp32 , delete devices and run discover again and the device name appeared, send a command and get device malfunction message (it waS POWERED OFF).
I used the Espalexa sample program and it works. So today a changed the device name to a new one and it was discovered( after a couple of attempts) and it works.
So I'm guessing that I was using the device name with Sinric in the past and it is still associated somehow to me.
possible?

**Comment by Aircoookie** [comment]
Yes, the Alexa implementation seems to get confused by multiple devices with the same name. Since Sinric is a different service, Alexa sees it as a separate device. It may even be possible that the Sinric device is still in the configuration even if you explicitely deleted it.
