### ISSUE TITLE
JSON format expected by ESPAlexa for RGB Colors ?

### ISSUE THREAD

**Issue by MopheusDG** [Aircoookie/Espalexa#56]
Hi, I'm trying to add my android application the capability of setting RGB colors on my ESPAlexa devices, and this raises a question, what JSON format is ESPAlexa expecting for RGB colors ?

I used to send a JSON like this for STATE and BRI:

JSON_STRING = { "on": true , "bri": 255 }

But not sure how to set RGB values now,
Thanks a lot.

**Comment by Aircoookie** [comment]
Hi! The Philips hue API (which Espalexa partly emulates) sadly has no way to send color as RGB. An alternative might be using Hue + Saturation mode as such: `{"on":true,"bri":255,"hue":18000,"sat":200}`, where hue is a 16 bit and sat an 8 bit value.

**Comment by MopheusDG** [comment]
Tx
