### ISSUE TITLE
No discovery at all, newest version, Echo Dot v.1

### ISSUE THREAD

**Issue by Salomon-MH** [Aircoookie/Espalexa#57]
As the title says, I get no discovery at all on my alexa.
This is the output:

> 16:08:34.968 -> Connecting to WiFi
> 16:08:34.968 -> Connecting....
> 16:08:35.446 -> Connected to CENSORED
> 16:08:35.446 -> IP address: CENSORED
> 16:08:35.446 -> Constructing device 1
> 16:08:35.446 -> Adding device 1
> 16:08:35.446 -> Constructing device 2
> 16:08:35.446 -> Adding device 2
> 16:08:35.446 -> Constructing device 3
> 16:08:35.481 -> Adding device 3
> 16:08:35.481 -> Constructing device 4
> 16:08:35.481 -> Adding device 4
> 16:08:35.481 -> Adding device 5
> 16:08:35.481 -> Espalexa Begin...
> 16:08:35.481 -> MAXDEVICES 10
> 16:08:35.481 -> Done
> 16:08:51.729 -> Got UDP!
> 16:08:51.729 -> M-SEARCH * HTTP/1.1
> 16:08:51.729 -> HOST: 239.255.255.250:1900
> 16:08:51.729 -> MAN: "ssdp:discover"
> 16:08:51.729 -> MX: 15
> 16:08:51.729 -> ST: urn:schemas-upnp-org:device:basic:1
> 16:08:51.729 -> 
> 16:08:51.729 -> 
> 16:08:51.729 -> Responding search req...
> 16:08:51.900 -> Got UDP!
> 16:08:51.900 -> M-SEARCH * HTTP/1.1
> 16:08:51.900 -> HOST: 239.255.255.250:1900
> 16:08:51.934 -> MAN: "ssdp:discover"
> 16:08:51.934 -> MX: 15
> 16:08:51.934 -> ST: urn:schemas-upnp-org:device:basic:1
> 16:08:51.934 -> 
> 16:08:51.934 -> 
> 16:08:51.934 -> Responding search req...
> 16:08:51.934 -> Got UDP!
> 16:08:51.934 -> M-SEARCH * HTTP/1.1
> 16:08:51.934 -> HOST: 239.255.255.250:1900
> 16:08:51.934 -> MAN: "ssdp:discover"
> 16:08:51.934 -> MX: 1
> 16:08:51.934 -> ST: urn:dial-multiscreen-org:service:dial:1
> 16:08:51.934 -> USER-AGENT: Google Chrome/73.0.3683.86 Windows
> 16:08:51.934 -> 
> 16:08:51.934 -> 
> 16:08:51.934 -> Got UDP!
> 16:08:51.934 -> M-SEARCH * HTTP/1.1
> 16:08:51.934 -> HOST: 239.255.255.250:1900
> 16:08:51.934 -> MAN: "ssdp:discover"
> 16:08:51.969 -> MX: 15
> 16:08:51.969 -> ST: urn:Belkin:device:**
> 16:08:51.969 -> 
> 16:08:51.969 -> 
> 16:08:52.109 -> Got UDP!
> 16:08:52.109 -> M-SEARCH * HTTP/1.1
> 16:08:52.109 -> HOST: 239.255.255.250:1900
> 16:08:52.109 -> MAN: "ssdp:discover"
> 16:08:52.109 -> MX: 15
> 16:08:52.109 -> ST: urn:Belkin:device:**
> 16:08:52.109 -> 
> 16:08:52.109 -> 
> 16:08:52.940 -> Got UDP!
> 16:08:52.940 -> M-SEARCH * HTTP/1.1
> 16:08:52.940 -> HOST: 239.255.255.250:1900
> 16:08:52.940 -> MAN: "ssdp:discover"
> 16:08:52.940 -> MX: 1
> 16:08:52.940 -> ST: urn:dial-multiscreen-org:service:dial:1
> 16:08:52.940 -> USER-AGENT: Google Chrome/73.0.3683.86 Windows
> 16:08:52.940 -> 
> 16:08:52.940 -> 
> 16:08:53.951 -> Got UDP!
> 16:08:53.951 -> M-SEARCH * HTTP/1.1
> 16:08:53.951 -> HOST: 239.255.255.250:1900
> 16:08:53.951 -> MAN: "ssdp:discover"
> 16:08:53.951 -> MX: 1
> 16:08:53.951 -> ST: urn:dial-multiscreen-org:service:dial:1
> 16:08:53.985 -> USER-AGENT: Google Chrome/73.0.3683.86 Windows
> 16:08:53.985 -> 
> 16:08:53.985 -> 
> 16:08:54.993 -> Got UDP!
> 16:08:54.993 -> M-SEARCH * HTTP/1.1
> 16:08:54.993 -> HOST: 239.255.255.250:1900
> 16:08:54.993 -> MAN: "ssdp:discover"
> 16:08:54.993 -> MX: 1
> 16:08:54.993 -> ST: urn:dial-multiscreen-org:service:dial:1
> 16:08:54.993 -> USER-AGENT: Google Chrome/73.0.3683.86 Windows

The /espalexa subpage is working as it should.
I'm using a custom OpenWRT router if you need that information.

Let me know if you need any more info. Thanks in advance.

**Comment by Aircoookie** [comment]
Thanks for the report! Try rebooting your Dot and attempt to do the discovery both via voice and the app. If that still doesn't work, it might be because of the custom router config, but let's try this first.

Echo Dot v1 is the slightly bigger one with the physical volume dial ring, right? Actually I have no report of that model being used with Espalexa before, so although it should work, I have no data on it.

**Comment by Salomon-MH** [comment]
Oh sorry, since you said that I looked it up, seems like it's a 2nd generation, not 1st! My fault!
I tried both, in-app and voice discovery. And actually I doubt that it's due to the router config as other Alexa libraries work just fine, just without color support (which is why I want to switch to this library). Any other ideas?

**Comment by Aircoookie** [comment]
Ok, gen 2 is known to work (in general). Did you also already tried rebooting the Dot? It already helped multiple other users who had the same issue :) Anyways, from you debug output it seems like the dot is sending SSDP discovery requests correctly, and the ESP is responding to them. The next step, which is failing, is the Echo requesting more device information via the /description.xml subpage...

**Comment by Salomon-MH** [comment]
Very, very strage! I did literally not change anything on my code at all, did not restart my Alexa yet, just ran a new search and suddenly the devices show up. I have no idea why it did not work in the first place and cannot reproduce the behavior... Amazon's Echo Dot seems to be quite strage.. Thanks though! 👍
