### ISSUE TITLE
Cant't control via Echo after tried to control via Alexa app

### ISSUE THREAD

**Issue by Obicom** [Aircoookie/Espalexa#61]
I have three lights with ESP8266 control and your great espalexa library. If I connect one first time all was fine to control the light via my Echos. Then I mad a "**mistake**" and tried to control via the Alexa smartphone app. I know that this will not work **BUT** after I tried I am no longer able to control the same light via the Echos. I deleted the devices and did a new "search" with Alexa. The devices was again discovered but I can do what I want I am no longer able to control this via the Echos. Anyone a idea why and what I could do to go back to the "initial" status?

**Comment by eos1d3** [comment]
This library works with Alexa apps very well. I tried a lot tests with it
and never find a problem.

Try to reboot your echo device and use the latest Alexa app.

**Comment by Obicom** [comment]
I work with the latest app version and restarted my Echos but without success.

**Comment by eos1d3** [comment]
With last dicovering issue I always deleted and discovered many many times
during tests without any problem.

And apps always work. I can even dim the on board led via Alexa app
together with on off operations.

**Comment by Obicom** [comment]
Ok, thank you for your support. The sketch that I am using and includes your library is not developed by my self. Maybe the developer has something changed by him self. I will go in contact with him and will try to find out.
