### ISSUE TITLE
How do I control the lamps?

### ISSUE THREAD

**Issue by SeriousOri** [Aircoookie/Espalexa#65]
Hello.
I have it installed on a Wemods D1 Mini, but I dont see in the sketch which PIN's I should use.
Where can I define the PIN's?
Or did I understand something wrong?

**Comment by Aircoookie** [comment]
Hi!
Espalexa is a library for interfacing with Alexa devices, it does not do anything useful like control lights on its own. You have to code the functionality yourself, one of the simplest possibilities for this is using `pinMode` and `digitalWrite` functions.

**Comment by SeriousOri** [comment]
Hi thanks
I dont know how to program well, but I'll take a closer look
