### ISSUE TITLE
Espalexa no longer works in Groups

### ISSUE THREAD

**Issue by CodeNoMore** [Aircoookie/Espalexa#72]
Points relating to this have been discussed in #69 and #71 but I wanted a more specific title as well as add my observations.
I am using Espalexa with the AsyncWebserver configuration and up until ~5/23/19 all was well. After that any Groups with Espalexa devices do not activate or sometimes one of the devices in the Group will and in some cases when you call the Group a Espalexa device that is not in the Group will activate. All devices have been forgotten and rediscovered and the Groups recreated to no avail. Also Espalexa devices cannot be controlled from the Android Alexa app. The status will show changed but no response on the actual device. Routines created using Espalexa devices do not work as well. Commercial devices are unaffected and Routines and Groups work as expected with those.
As stated before in earlier issues this is most likely caused by some update that Amazon applied however as previously mentioned commercial devices are unaffected so there is some issue with how Espalexa handles the handshaking with the Echo's. It also does not seem to be related to the Gen of the Echo
Thanks.

**Comment by Aircoookie** [comment]
Thanks for the detailed issue description! I've also been experiencing this:
- Single device control via voice - OK
- Android app displays device changes, but trying to control says device is unreachable immediately
- Can be added to groups, but won't work

I'll try and fix this ASAP, but it might take a few days :) Can't promise that the groups will work though, since that is all Echo-side code...

**Comment by eos1d3** [comment]
Last time you told me the request has an unique id. Is this the one you did
not use and cause the problem?

**Comment by ChezanV** [comment]
From sonoff

Edit Espalexa.h

Add 2 functions

`uint32_t EncodeLightId(uint8_t idx)
{
  uint8_t mac[6];
  WiFi.macAddress(mac);
  uint32_t id = (mac[3] << 20) | (mac[4] << 12) | (mac[5] << 4) | (idx & 0xF);
  return id;
}

uint32_t DecodeLightId(uint32_t id) {
  return id & 0xF;
}`
On line 533
`for (int i = 0; i<currentDeviceCount; i++)
        {
		  q = EncodeLightId(i+1);
          jsonTemp += "\"" + String(q) + "\":";
          jsonTemp += deviceJsonString(i+1);
          if (i < currentDeviceCount-1) jsonTemp += ",";
        }`
On line 459
`    if (req.indexOf("state") > 0) //client wants to control light
    {
      server->send(200, "application/json", "[{\"success\":true}]"); //short valid response

      int devId1 = req.substring(req.indexOf("lights")+7).toInt();
      EA_DEBUG("ID 1 "); EA_DEBUGLN(devId1);
	  int devId = DecodeLightId(devId1);
	  EA_DEBUG("ID 2 "); EA_DEBUGLN(devId);
      devices[devId-1]->setPropertyChanged(EspalexaDeviceProperty::none);
      
      if (body.indexOf("false")>0) //OFF command
....
.....`

**Comment by Aircoookie** [comment]
@ChezanV thank you very much, I will try and get this fixed by tomorrow!

**Comment by Aircoookie** [comment]
I've just releases v2.4.3 which implements the Sonoff workaround.
Groups and app control seem to work again now.
It is once again required to delete all Espalexa devices, and then rediscover them.

Let me know if there are any issues!

**Comment by Aircoookie** [comment]
By the way, I've experienced the minor issue of Alexa saying/the app displaying that no new devices were found. The devices still appeared in the list though.

**Comment by CodeNoMore** [comment]
I have applied the 2.4.3 library to all my devices and Groups work again as well as the Alexa Android app.
No issues so far and all is good.
Thank you.

**Comment by anrada73** [comment]
Top! Thank you.

**Comment by ChezanV** [comment]
I confirm. It's working without any issue.
17 devices emulated by 3 boards
