### ISSUE TITLE
Configure devices name in the webpage

### ISSUE THREAD

**Issue by xfce** [Aircoookie/Espalexa#8]
Hi, all.
     Is it possible to have a function, that user can configure the devices name by theirself use the webpage instead of change the code than compile and flash.

**Comment by Aircoookie** [comment]
Hi,
the first thing you could do is change the device name in the Alexa app.

For changing the name while the program is running I can add the EspalexaDevice::setName() function. Will do in the next few hours. You'd still need to add the program logic for user configuration though. If you wanted to deploy Espalexa on a larger scope than for hobbyist use, you'd have some sort of code for storing WiFi name and password from the user. Now you could also store their desired device name(s) and apply them.

That said, Espalexa is a library designed to connect your own program to Alexa. It is neither meant nor useful to use it stand-alone and the examples are only meant to convey how to use the library.

**Comment by xfce** [comment]
@Aircoookie  
OK, thanks. I have done this
