### ISSUE TITLE
can be used as "input" instead of "on/off"?

### ISSUE THREAD

**Issue by robertaccess** [Aircoookie/Espalexa#95]
The library is working well, I use something like:

> 
  digitalWrite(0, HIGH);
  delay(150);
  digitalWrite(0, LOW);

the impulse is working as is should (I think the delay is not right, seems to be longer), but after that alexa say that is a problem with the device.

Can I stop alexa from check the device status, to not report that error, or I can use another code for a quick impulse?

Thank you very much!

**Comment by SiddhantShah2001** [comment]
The Delay Functions stops the Flow of the Program so the ESP Board can not communicate with Echo in that period of time. Hence, the Errors.

Use the millis() timer funtion or a timer library (i would suggest CountUpDownTimer https://github.com/AndrewMascolo/CountUpDownTimer)
