### ISSUE TITLE
Not discovered from Alexa Android app

### ISSUE THREAD

**Issue by peppeve** [Aircoookie/Espalexa#96]
Using esp32 (DevKit V1), the app don't find any device, the webserver show that everything is ok. 
this is the otput from debug:

```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8

Connecting to WiFi
Connecting....
Connected to TP-LINK_52BE
IP address: 192.168.1.116
Constructing device 1
Adding device 1
Espalexa Begin...
MAXDEVICES 10
Done
HTTP Req espalexa ...

Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1


Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
```

this is the webserver:

```
Hello from Espalexa!

Value of device 1 (My Light 1): 0 (Dimmable light)

Free Heap: 261240
Uptime: 41695

Espalexa library v2.4.4 by Christian Schwinne 2020
```

**Comment by peppeve** [comment]
Same problem seeking from alexa [website](https://alexa.amazon.it), nothing discovered.

**Comment by peppeve** [comment]
@Aircoookie no solution?

**Comment by eos1d3** [comment]
I tried the latest version. Discovery works 100% with ESP32.

**Comment by peppeve** [comment]
@eos1d3 you use the example sketch?

**Comment by eos1d3** [comment]
Right. The Fullyfeatured one.

If you are using PlatformIO, delete .pio folder first. It may contain old
version.

**Comment by peppeve** [comment]
@eos1d3 i use arduino ide 1.8.10, you seeking with alexa app or with phisical alexa?

**Comment by eos1d3** [comment]
Via Alexa app. Add light device and choose other.

**Comment by peppeve** [comment]
@eos1d3 nothing. `Connecting to WiFi
Connecting....
Connected to TP-LINK_52BE
IP address: 192.168.1.218
Constructing device 1
Adding device 1
Constructing device 2
Adding device 2
Constructing device 3
Adding device 3
Constructing device 4
Adding device 4
Adding device 5
Espalexa Begin...
MAXDEVICES 10
Done
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1


Got UDP!
Got UDP!
Got UDP!
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 1
ST: urn:dial-multiscreen-org:service:dial:1
`
everything seem to be fine, but alexa tell me nothing found.

**Comment by eos1d3** [comment]
I am using Alexa gen 3.

**Comment by eos1d3** [comment]
I think it won't work then.

**Comment by Aircoookie** [comment]
Yep, unfortunately that is the case. The protocol is local and an online hardware Echo device ist required to discover/control.

From the readme:

> The library aims to work with every Echo on the market, but there are a few things to look out for.
Espalexa only works with a genuine Echo speaker, it probably wont work with Echo emulators, RPi homebrew devices or just the standalone app.
