### ISSUE TITLE
How to use Espalexa and WiFi Manager On Demand Config Portal

### ISSUE THREAD

**Issue by SiddhantShah2001** [Aircoookie/Espalexa#99]
### PROCEDURE:
**STEP 1:**
**Go to:** My PC > Documents > Arduino > libraries > Espalexa > src < and Open up all three Files in the Folder named as:
**"Espalexa.h"
"EspalexaDevice.h"
"EspalexaDevice.cpp"**
in a Simple Text Editor or a Code Editor (I used **Sublime Text**).

**STEP 2:**
In File: **"Espalexa.h":**
Add Line: 
```
void close()
  {
    server->close();
  }
```
  before the line:

  `~Espalexa(){delete devices;}`

In File: **"EspalexaDevice.h":**
Add Line:
```
void EspalexaDevice::close()
{
}
```

at the End, after the function:
```
void EspalexaDevice::doCallback()
{
  if (_callback != nullptr) {_callback(_val); return;}
  if (_callbackDev != nullptr) {_callbackDev(this); return;}
  if (_callbackCol != nullptr) _callbackCol(_val, getRGB());
}
```

In File: **"EspalexaDevice.cpp":**
Add Line:
`void close();`

Just after the Line:
`uint8_t getLastValue();`

**STEP 3:** Last Step!
Add Line:
`espalexa.close();`

just before you call the Config Portal.
Also Remember to add a reset function at the end or atleast the begin function for Espalexa.
i.e.:

```
  espalexa.close();
  WiFiManager wifiManager;
  wifiManager.startConfigPortal();
  ESP.reset(); // I would recommend this one than the one below.

or

  espalexa.close();
  WiFiManager wifiManager;
  wifiManager.startConfigPortal();
  espalexa.begin();
```

**That's It!**

**Comment by GoTVm** [comment]
This guide seems to work so far, it's the only solution but sadly it doesn't pop up if you Google search the issue. Had to scour both GitHub repos and see if anybody else had this issue.

**Comment by tablatronix** [comment]
Whats the exact conflict here ?

**Comment by GoTVm** [comment]
You need to call espalexa.close() before you call the OnDemandConfig portal in your main sketch. Once it's done and it closes, you can espalexa.begin() again.

**Comment by pbpatwari** [comment]
Stuck at Step 3, getting error 'espalexa' does not name a type on line on espalexa.close();...i tried to change it Espalexa.close(); bt to no effect. kindly help
